[development]
address = "localhost"
port = 8000
workers = 16
log = "debug"
limits = { forms = 65536 }

[staging]
address = "0.0.0.0"
port = 80
workers = 16
log = "normal"
limits = { forms = 65536 }

[production]
address = "0.0.0.0"
port = 80
workers = 16
log = "critical"
limits = { forms = 65536 }